server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  # 单页应用前端路由
  location / {
    try_files $uri /index.html;
  }

  # 前端请求 /api/... 走后端
  location /api/ {
    proxy_pass http://java-app:7777/;     # 容器网络下的服务名和端口
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    # 去掉 /api/ 前缀
    rewrite ^/api/(.*)$ /$1 break;
  }
}
